apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432  # The port the database container listens on
  clusterIP: None  # This will give it a DNS name within the cluster

