global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask-web-app'
    static_configs:
      - targets: ['flask-web-app-service:5000']  # Scraping Flask app metrics from the service (Port 5000)

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-service:5432']  # Scraping PostgreSQL metrics from the service (Port 5432)

